### ISSUE TITLE
Code missing in repo

### ISSUE THREAD

**Issue by gailjkm** [ivansjdev/openpipe-api#1]
I missing something basically.
I see in the repository only a README and a subfolder with the neccessary images. 

But I cannot see any code files. 
When I look at the histroy, they seems to be checked in. 
Do I missunderstand something, or what is on?

**Comment by ivansjdev** [comment]
Yeah, sorry about that. I'd love to share the code with the community, but it's part of a project for my current company, so I can't make it public. My hands are tied on this one.
Just to clarify, at the end of the day, this repo is just a demo of what's possible.

If you've got any questions about the project or anything else, feel free to ask!
